set(SDK_PATH "/Users/brrodrig/SimplicityStudio/SDKs/simplicity_sdk_3")
set(COPIED_SDK_PATH "simplicity_sdk_2025.6.1")
set(PKG_PATH "/Users/brrodrig/.silabs/slt/installs")

add_library(slc_bootloader-apploader_dcb OBJECT
    "../${COPIED_SDK_PATH}/hardware/driver/configuration_over_swo/src/sl_cos.c"
    "../${COPIED_SDK_PATH}/platform/bootloader/communication/apploader/btl_apploader.c"
    "../${COPIED_SDK_PATH}/platform/bootloader/communication/apploader/btl_apploader_common.c"
    "../${COPIED_SDK_PATH}/platform/bootloader/core/btl_bootload.c"
    "../${COPIED_SDK_PATH}/platform/bootloader/core/btl_core.c"
    "../${COPIED_SDK_PATH}/platform/bootloader/core/btl_main.c"
    "../${COPIED_SDK_PATH}/platform/bootloader/core/btl_parse.c"
    "../${COPIED_SDK_PATH}/platform/bootloader/core/btl_reset.c"
    "../${COPIED_SDK_PATH}/platform/bootloader/core/flash/btl_internal_flash.c"
    "../${COPIED_SDK_PATH}/platform/bootloader/debug/btl_debug.c"
    "../${COPIED_SDK_PATH}/platform/bootloader/debug/btl_debug_swo.c"
    "../${COPIED_SDK_PATH}/platform/bootloader/driver/btl_driver_util.c"
    "../${COPIED_SDK_PATH}/platform/bootloader/parser/gbl/btl_gbl_custom_tags.c"
    "../${COPIED_SDK_PATH}/platform/bootloader/parser/gbl/btl_gbl_format.c"
    "../${COPIED_SDK_PATH}/platform/bootloader/parser/gbl/btl_gbl_parser.c"
    "../${COPIED_SDK_PATH}/platform/bootloader/security/btl_crc16.c"
    "../${COPIED_SDK_PATH}/platform/bootloader/security/btl_crc32.c"
    "../${COPIED_SDK_PATH}/platform/bootloader/security/btl_security_aes.c"
    "../${COPIED_SDK_PATH}/platform/bootloader/security/btl_security_ecdsa.c"
    "../${COPIED_SDK_PATH}/platform/bootloader/security/btl_security_sha256.c"
    "../${COPIED_SDK_PATH}/platform/bootloader/security/btl_security_tokens.c"
    "../${COPIED_SDK_PATH}/platform/bootloader/security/ecc/ecc.c"
    "../${COPIED_SDK_PATH}/platform/bootloader/security/sha/btl_sha256.c"
    "../${COPIED_SDK_PATH}/platform/bootloader/security/sha/crypto_sha.c"
    "../${COPIED_SDK_PATH}/platform/bootloader/security/sha/cryptoacc_sha.c"
    "../${COPIED_SDK_PATH}/platform/bootloader/security/sha/se_sha.c"
    "../${COPIED_SDK_PATH}/platform/common/src/sl_assert.c"
    "../${COPIED_SDK_PATH}/platform/common/src/sl_core_cortexm.c"
    "../${COPIED_SDK_PATH}/platform/common/src/sl_syscalls.c"
    "../${COPIED_SDK_PATH}/platform/Device/SiliconLabs/EFR32MG24/Source/startup_efr32mg24.c"
    "../${COPIED_SDK_PATH}/platform/Device/SiliconLabs/EFR32MG24/Source/system_efr32mg24.c"
    "../${COPIED_SDK_PATH}/platform/driver/debug/src/sl_debug_swo.c"
    "../${COPIED_SDK_PATH}/platform/driver/gpio/src/sl_gpio.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/dmadrv/src/dmadrv.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_acmp.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_burtc.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_cmu.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_dbg.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_emu.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_eusart.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_gpcrc.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_gpio.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_i2c.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_iadc.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_ldma.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_letimer.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_msc.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_opamp.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_pcnt.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_prs.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_rmu.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_system.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_timer.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_usart.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_vdac.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_wdog.c"
    "../${COPIED_SDK_PATH}/platform/peripheral/src/sl_hal_gpio.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/cs/antenna_offset/sl_rail_util_cs_antenna_offset.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/cs/gdcomp/sl_rail_util_cs_gdcomp.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/cs/gdcomp/sl_rail_util_cs_gdcomp_tables.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/pa-conversions/pa_conversions_efr32.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/pa-conversions/pa_curves_efr32.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_aox/sl_rail_util_aox.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_built_in_phys/efr32xg24/sl_rail_ble_config_38M4Hz.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_built_in_phys/efr32xg24/sl_rail_ble_config_39MHz.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_built_in_phys/efr32xg24/sl_rail_ble_config_40MHz.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_built_in_phys/efr32xg24/sl_rail_ieee802154_config_38M4Hz.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_built_in_phys/efr32xg24/sl_rail_ieee802154_config_39MHz.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_built_in_phys/efr32xg24/sl_rail_ieee802154_config_40MHz.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_built_in_phys/efr32xg24/sl_rail_rfsense_ook_config_38M4Hz.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_built_in_phys/efr32xg24/sl_rail_rfsense_ook_config_39MHz.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_built_in_phys/efr32xg24/sl_rail_rfsense_ook_config_40MHz.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_built_in_phys/sl_rail_phy_overrides.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_dma/sl_rail_util_dma.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_sequencer/sl_rail_util_sequencer.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_attestation.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_cipher.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_entropy.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_hash.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_key_derivation.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_key_handling.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_signature.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_util.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sli_se_manager_mailbox.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/se_aes.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sl_mbedtls.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_driver_common.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_driver_init.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_aead.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_builtin_keys.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_cipher.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_key_derivation.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_key_management.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_mac.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_signature.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_opaque_driver_aead.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_opaque_driver_cipher.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_opaque_driver_mac.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_opaque_key_derivation.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_driver_aead.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_driver_cipher.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_driver_hash.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_driver_mac.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_key_derivation.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_version_dependencies.c"
    "../${COPIED_SDK_PATH}/platform/service/clock_manager/src/sl_clock_manager.c"
    "../${COPIED_SDK_PATH}/platform/service/clock_manager/src/sl_clock_manager_hal_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/device_init/src/sl_device_init_dcdc_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/device_init/src/sl_device_init_emu_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/device_init/src/sl_device_init_hfxo_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/device_init/src/sl_device_init_lfxo_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/device_manager/clocks/sl_device_clock_efr32xg24.c"
    "../${COPIED_SDK_PATH}/platform/service/device_manager/src/sl_device_clock.c"
    "../${COPIED_SDK_PATH}/platform/service/device_manager/src/sl_device_gpio.c"
    "../${COPIED_SDK_PATH}/platform/service/interrupt_manager/src/sl_interrupt_manager_cortexm.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_dynamic_reservation.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_pool.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_pool_common.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_region.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_retarget.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sli_memory_manager_common.c"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/apploader/src/sli_apploader_lib_adaptation.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/aes.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/constant_time.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/platform.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/platform_util.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_client.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_util.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/threading.c"
    "../${COPIED_SDK_PATH}/util/third_party/trusted-firmware-m/lib/fih/src/fih.c"
    "../${COPIED_SDK_PATH}/util/third_party/trusted-firmware-m/platform/ext/target/siliconlabs/hse/sli_se.c"
    "../autogen/sl_device_init_clocks.c"
)

target_include_directories(slc_bootloader-apploader_dcb PUBLIC
   "../config"
   "../autogen"
    "../${COPIED_SDK_PATH}/platform/Device/SiliconLabs/EFR32MG24/Include"
    "../${COPIED_SDK_PATH}/protocol/bluetooth/apploader/inc"
    "../${COPIED_SDK_PATH}/platform/common/inc"
    "../${COPIED_SDK_PATH}/platform/bootloader"
    "../${COPIED_SDK_PATH}/platform/bootloader/communication"
    "../${COPIED_SDK_PATH}/platform/bootloader/debug"
    "../${COPIED_SDK_PATH}/platform/bootloader/parser"
    "../${COPIED_SDK_PATH}/platform/bootloader/api"
    "../${COPIED_SDK_PATH}/platform/bootloader/security"
    "../${COPIED_SDK_PATH}/platform/service/clock_manager/inc"
    "../${COPIED_SDK_PATH}/platform/service/clock_manager/src"
    "../${COPIED_SDK_PATH}/platform/CMSIS/Core/Include"
    "../${COPIED_SDK_PATH}/hardware/driver/configuration_over_swo/inc"
    "../${COPIED_SDK_PATH}/platform/driver/debug/inc"
    "../${COPIED_SDK_PATH}/platform/service/device_manager/inc"
    "../${COPIED_SDK_PATH}/platform/service/device_init/inc"
    "../${COPIED_SDK_PATH}/platform/emdrv/dmadrv/inc"
    "../${COPIED_SDK_PATH}/platform/emdrv/dmadrv/inc/s2_signals"
    "../${COPIED_SDK_PATH}/platform/emdrv/common/inc"
    "../${COPIED_SDK_PATH}/platform/emlib/inc"
    "../${COPIED_SDK_PATH}/platform/driver/gpio/inc"
    "../${COPIED_SDK_PATH}/platform/peripheral/inc"
    "../${COPIED_SDK_PATH}/platform/service/interrupt_manager/inc"
    "../${COPIED_SDK_PATH}/platform/service/interrupt_manager/src"
    "../${COPIED_SDK_PATH}/platform/service/interrupt_manager/inc/arm"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/config"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/config/preset"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/inc"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/include"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/inc"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/inc"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/common"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/protocol/ble"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/protocol/ieee802154"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/protocol/wmbus"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/protocol/zwave"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/chip/efr32/efr32xg2x"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/protocol/sidewalk"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_aox"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/cs/antenna_offset"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_built_in_phys/efr32xg24"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/cs/gdcomp"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_dma"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/pa-conversions"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/pa-conversions/efr32xg24"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/inc"
    "../${COPIED_SDK_PATH}/util/third_party/trusted-firmware-m/lib/fih/inc"
    "../${COPIED_SDK_PATH}/util/third_party/trusted-firmware-m/platform/include"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sli_psec_osal/inc"
)

target_compile_definitions(slc_bootloader-apploader_dcb PUBLIC
    "EFR32MG24A410F1536IM48=1"
    "SL_CODE_COMPONENT_SYSTEM=system"
    "SE_MANAGER_CONFIG_FILE=\"btl_aes_ctr_stream_block_cfg.h\""
    "BOOTLOADER_APPLOADER=1"
    "BOOTLOADER_SUPPORT_COMMUNICATION=1"
    "BOOTLOADER_ENABLE=1"
    "BOOTLOADER_SECOND_STAGE=1"
    "SL_RAMFUNC_DISABLE=1"
    "__START=main"
    "__STARTUP_CLEAR_BSS=1"
    "SYSTEM_NO_STATIC_MEMORY=1"
    "SL_CODE_COMPONENT_CLOCK_MANAGER=clock_manager"
    "SL_COMPONENT_CATALOG_PRESENT=1"
    "SL_CODE_COMPONENT_DMADRV=dmadrv"
    "SL_CODE_COMPONENT_GPIO=gpio"
    "SL_CODE_COMPONENT_HAL_COMMON=hal_common"
    "SL_CODE_COMPONENT_HAL_GPIO=hal_gpio"
    "SL_CODE_COMPONENT_INTERRUPT_MANAGER=interrupt_manager"
    "CMSIS_NVIC_VIRTUAL=1"
    "CMSIS_NVIC_VIRTUAL_HEADER_FILE=\"cmsis_nvic_virtual.h\""
    "MBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>"
    "MBEDTLS_PSA_CRYPTO_CLIENT=1"
    "MBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>"
    "SL_RAIL_LIB_MULTIPROTOCOL_SUPPORT=0"
    "SL_RAIL_UTIL_CS_GDCOMP_HP_PA_DBM=10"
    "SL_RAIL_UTIL_CS_GDCOMP_LP_PA_DBM=0"
    "SL_RAIL_UTIL_PA_CONFIG_HEADER=<sl_rail_util_pa_config.h>"
    "SL_CODE_COMPONENT_SE_MANAGER=se_manager"
    "SL_CODE_COMPONENT_CORE=core"
    "SL_RAIL_3_API=1"
    "SL_CODE_COMPONENT_PSEC_OSAL=psec_osal"
)

target_link_libraries(slc_bootloader-apploader_dcb PUBLIC
    "-Wl,--start-group"
    "gcc"
    "c"
    "m"
    "nosys"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/bluetooth/apploader/build/gcc/cortex-m33/release/libapploader.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/platform/radio/rail_lib/autogen/librail_release/librail_efr32xg24_gcc_release.a"
    "-Wl,--end-group"
)
target_compile_options(slc_bootloader-apploader_dcb PUBLIC
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:C>:-mthumb>
    $<$<COMPILE_LANGUAGE:C>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:C>:-mfloat-abi=hard>
    $<$<COMPILE_LANGUAGE:C>:-mcmse>
    $<$<COMPILE_LANGUAGE:C>:-Wall>
    $<$<COMPILE_LANGUAGE:C>:-Wextra>
    $<$<COMPILE_LANGUAGE:C>:-Os>
    $<$<COMPILE_LANGUAGE:C>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:C>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:C>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:C>:-g>
    $<$<COMPILE_LANGUAGE:C>:-Wno-ignored-qualifiers>
    $<$<COMPILE_LANGUAGE:C>:-Wno-sign-compare>
    $<$<COMPILE_LANGUAGE:C>:-fno-lto>
    $<$<COMPILE_LANGUAGE:C>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:CXX>:-mthumb>
    $<$<COMPILE_LANGUAGE:CXX>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:CXX>:-mfloat-abi=hard>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>
    $<$<COMPILE_LANGUAGE:CXX>:-mcmse>
    $<$<COMPILE_LANGUAGE:CXX>:-Wall>
    $<$<COMPILE_LANGUAGE:CXX>:-Wextra>
    $<$<COMPILE_LANGUAGE:CXX>:-Os>
    $<$<COMPILE_LANGUAGE:CXX>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:CXX>:-g>
    $<$<COMPILE_LANGUAGE:CXX>:-Wno-ignored-qualifiers>
    $<$<COMPILE_LANGUAGE:CXX>:-Wno-sign-compare>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-lto>
    $<$<COMPILE_LANGUAGE:CXX>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:ASM>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:ASM>:-mthumb>
    $<$<COMPILE_LANGUAGE:ASM>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:ASM>:-mfloat-abi=hard>
    "$<$<COMPILE_LANGUAGE:ASM>:SHELL:-x assembler-with-cpp>"
)

set(post_build_command ${POST_BUILD_EXE} postbuild "./bootloader-apploader_dcb.slpb" --parameter build_dir:"$<TARGET_FILE_DIR:bootloader-apploader_dcb>")
set_property(TARGET slc_bootloader-apploader_dcb PROPERTY C_STANDARD 17)
set_property(TARGET slc_bootloader-apploader_dcb PROPERTY CXX_STANDARD 17)
set_property(TARGET slc_bootloader-apploader_dcb PROPERTY CXX_EXTENSIONS OFF)

target_link_options(slc_bootloader-apploader_dcb INTERFACE
    -mcpu=cortex-m33
    -mthumb
    -mfpu=fpv5-sp-d16
    -mfloat-abi=hard
    -T${CMAKE_CURRENT_LIST_DIR}/../autogen/linkerfile.ld
    --specs=nano.specs
    "SHELL:-Xlinker -Map=$<TARGET_FILE_DIR:bootloader-apploader_dcb>/bootloader-apploader_dcb.map"
    "SHELL:-Wl,--wrap=_free_r -Wl,--wrap=_malloc_r -Wl,--wrap=_calloc_r -Wl,--wrap=_realloc_r"
    -fno-lto
    -Wl,--gc-sections
)

# BEGIN_SIMPLICITY_STUDIO_METADATA=eJztvQmT3DiSJfxXymRtn03vVgbjzkxtVbdVS6ru3E9ZkilVs9s2GqMhSEQEK3k1jzxqrP/7AuB94yQZbTNTLSkiSPf3HA7AcTn+683nL5/+94d3X/Uvnz59ffP2zX99e/Plw8efvt79+we9/NO3N2+/vVksvr3555vv83cePv365d2HB/TaD39+cezvnmAQWp7747c3q8Xy25vvoGt4puWe0Be/fv356ubbmz//6Zv7gx94v0Ej+g797cMgen0w0N/omfT7b2/QQ99998PRs00YfOcCB/9oeO7ROqW/4V8tG2a/HSJbB75vewC9oCdPLs4IQBxY6Gf86Fvt1xCh0w5B4JmBddIeLMe3LcNC6qPYtDztaac/e8Fj6AMDagfPixJxV4Vg0zhoiXCtS6PWBc/wAqgbxxFglTV1wjHhIT6Ng6eiqhVQiB96sgyoW64V6fbxxRulEPv1dkENgGXrcYT+AN7LWDi7lHaBPILYjhAtXJ9QjdTPIDChi6qi+jKn0T5sW9MB49u2qrQVJHrEDJ5GgdZQ1V15cA0Ln0esNU2Fw0VqhDpwI+i6QPeOxxBG4xdwH4RhAv4ELukPemSYNfnjQKvpoir2k2l4jj9JcTdUd3aJAIa6EQV6GAUQOPrB9ozHcXrIPs2tcP0QeUXw6kfj1PhWdTQ9uWmYxhQ9eU1vF1QHOl7wqjvABaeR4sY+rcNVKYT/iFFMPR7WftWUdg3gCQcB05i3oZzGb6ETT+G2VbU0QM8ThcpnulDZOUAzssPRir6hbghYymlkfA2tCcwftGTE2zb6BXHknaBbGv5Wfl6EtoG6DxDB/Ika6YUR5E0i+qcSpilIrUCjNdTmJVImW8P65esH/R3qtT0XulGoqFgysE1l3VFW+pRugAjYniqHyZB1qaRpGAwcQ4QLteXcqbMDoVWroXoqSLkd+xTTYo0C4IZHL3CmQ90KoRM/idrGtnO70l6Mh9iyI8udBmu38lbMtuU+wgB/s7BNpQBrmlrRYKTpHKoFQ6Vw6qqGe6wwV6iH5qO+Xq53i/1i1dWD+TaIsGtX+q/KE+9JU1P6vfHEg4UUeu5HcAgrjzUe/PDzl836/q/rbe2xpkQvDmo6W/rW8DWMoKPDY7BZO6f1VlGz22FRLTOdllhIK5lBy5lqCRWtDas2QC8CQRT7F8KvDWydYC346Cj8O9ewY3Ow9HNNYLtaHle7zd5ytjeK2i8xG6WMtG7IA66Qv6gDw/Evg2MOlZ4bVBV0SqcGQyZmhzgAzoVwy7GysIuMy2GXYKVmZzjxhXBLkVIzw9N1F0Itg0rPDcl3j96l0CvQ0jN0AHovNALLj7zgUog2QNPz9W37UlimUKm5wYtpYyBjGwPjEAWGl0IuB0vN7xgGxqW0MjlWanYn3wgupYvIsTKwsy6l6DKoTNx037uYqlfBS83yfLyc2pdjZWD3cjnkXti4WetLaVdSpPTMwMVE1RlUem4GMM7wUtjlYKn5PcLX0ACqJsFlEyyhpWZoowj8QuhlUJm4vRzApYyFynCZOaJR1NFyL2bCrA02PWcYWQ68mGIt0NIzvKA4xmaOY+zLiWNs1jjGAZZ98F4uhF4JLT1DH5wPlzN9XYZLzzG8lJAtRUrNzDfcSxkCZlDpuQWX0v2lSFmY6aF1coF9QQzLiKmZhkYAIuPsA/NCiFYB0/OEl9VTVPDSs7yYeeyQcR47REMtZWcSpJPLwbLwu5xF3AIsNb9LGkGwjx/iSxpAxOwjiEtaRGJfQ3oywaXUvAwqNbdnU9l+bdncMqhD3Jx09/W8aZVRDm00rO9NnDOxNrBU+wxbvmx81fyingzBcTy3by+s5RqNPbDV4wIHa7KWLIGvIYxaAUTrRWt4JtQNG4ShdbQMgI+VzwN9B7BeNtZs6XQi6y8d6MaTzctUiyND0o8XsYPTdeRVxAWWoRqA35oH5gLLIGYffTNZwNtAnaMZwh1M1q3WMQctXWcdLz5sF082RVNFXGDR+rq45oGRYKjHSmvKRKcPUpYIplbBMuxJ+I8IvjjzQF5HNOBZeGnXtlUdJWTEXkbT611DAVQBqC+ICqGBKEev/aeJwjNoOUdUMmOaOwE9N5UVize1jJOG4GhVZI3wtUkCGMZ8eZTA9VIJ4Rw5FKh6weOEIei59W4/NwJVZLQkJuqzKEg0e93W4Vy1MYBGvRerD9sNY04Fh+BoKaTeEsPPzKioMti0ZVT3vVQOOUA1o9Jow9bTP1cen1+j0AGPlhA0zHBWrXQ7Olo6E54qpHK1/kFGC/e5ksnRMdacufLp7I46CUXeI3Tn620FPGpCr/6Ma0+OboCOERir2TXQOahh8Jv1DMEnoKjAz8x/clBUbjM/8CueNmlmDtQCj23WCs9PxG46Ud4/T5BD7h8gVFJLz8BeFYZaLkdr4Bwc8ZUTZpP54wshV4JLz3EGFZau5NrWLXtKDtj2ARiPl0KvAphnqFjRMjvWrQjZWjAE/KnRJjUTxpOnSC7QGVTbBI3WAmygOyo/PX1ZdtBgLkI8pd/f9xxtEJ6H+x3LjWDgAlsnz8+goDEzjYDR2vENNl21V6Yv9H5KnK1UJn8uRVbHNBTi4lXOGUHP8AzAdoA1jyAmhZ3hGYDtgyCclblzQAPAAxjCydZ/24DngGj8eyZNTxnPAOwztP2ZRLIp8AIRlavMCHkOiKpyzgh4DmgAeN7czwh7GdMA/Ng/BejlOaEvQRoCP494tkDOFcYC3xoahpBo6Qim2/RcYovgag1MAwUFEb4Ab7GcEf4KJppmVZ8yo10LgSqoHgZYVTpO1otsxjNh0g1uoExy/0ua6jn0142qUYJGzSaMvACc5lRTWrGxDtUr1xh2xosKL6Rga9FL9wrWb9WgY0wuCxucXsIPzSCyJzi0CqKhGaXsLrT5oc9Q0TCYga/Vbc/saUkb0z8RdjrYw9Ng6CHdiFEdd/QInOawaJVQ0xAwrQPg4EQYfgeLBXMYQbfwKbBRUUk7lFlSKbCxUJm+BnZToVkkKhXiLKkU2KiolOvXLPnUAA5OGzNvkkcKh67cIHf+ZJetDWyTb5zvaDktURY3Vd1OaWsVMPnpiTrC/p3m+EBd+Q39DCYbqPfx6oA5QK75kh5OtkeIvthKQNk3eDcP1g658ayKOztWVkfI5sZz5NQCkb1JbBm9kAvOpLVw2d1/GOrUNaXKLasqdYRDbUD6PMkMPWdCGUA1Vb5itYlrR80MaZWvI2Qp1zkTak9JTlOuyYWFTEWb5Ht4OU13CVaHTRIu9XKuwpXXHOL7HvvbQoY6U748ch6OhhHVvKwGkrLy5LdRz5xY17U2fbQmvCuEklXHHSF9pKZMdU/JqivFfR+tKTPfUtJqz3hL04wzhF3F7fDTj1PK9qhGKnWUjLVy/twKkKx1c/7cSihZa+j8ydld5LiCCbKcFsR+RDe8ag8pqjsIKhfIttrdcEIr1F3ESX+ygiiefj6mYQbSPAKc/KIVK1WWsaa3NdTMk3cXUiX9gnUJVslm6CjMQlHqUyejGeLZj1hCq+NAxwte5c3oVOVNbdYqmsymTYxDflN9Qzdf0U+oGcJbbYKn5KTJBTDtwj0421kTM+15tV7GPVgZyziAEQhO022wZirYMljG0py6hacqRpq2vWYS3/PsOXvqAF4OthdDk6s2ni6lkS2gqplbn3X1TWNW4dqbGvECyJWgsvajqNWGLtnhanhuFHiTj71a+dLBlr/f4t39w91D326Ld4PnPNPs1AP5CMmwcurcrISthinlObWbwPpTEpLHnxDaCWtOJ40Srl4W0e/Eq+DLZNumWihUQVGUwmm6/HCdJXBqSxBXR0+yoTqbzZzQlzH1onf8WAeB83QzI/QVTPIbyZZ0BVQbzjmWDCbe2J1mB0i2ReeTsd37uqXtZMhUTORTFd75SlEJlIRJILxpQNxFptzzkloJQ8icQ+0Olyk3gpTJph5Bve2DuYWBjhk89TYwDqg/we4+iZCpvIdw1BIMxH0KOLK8p2qOdXYr39D6TAJk6lsHK/YhHpcT0JoIeVZkUoPPhV8BR0Lr2nI9DXuTA6c8JpvYp3SxAew4ICulvbGtQ28a+v6bEaCjA8Pxp2tKEHzShpSA9Bw5Q08dYnxt3hzw5kj6ARtOPAu4KY5+sOZhspOUFbApjn6wcCaWhTSWhcmderPAm0Pph3zyjWAeVS1HMgR4upi6hrc1mq7BtdbzsG6KYwAsMGeCNgXSD9dGQcks4GZABuDC5MLUWSAusPSDxve4zwFwiqMfrOeDmcQ5OZJ+wOQq+TngzYAMwA0mO+teRRsM3XyBHgpmEjkENJFDclvoLPAWUPohz6cxo2zK5hOcUcZm5BLjOeDNgPTDJfcSzwFuBoQtO8jAjbjZ4HWyCQdMkMw0FEBoRtFzwJsjGRhFn6152DcDMjzonwXatmNMLWDJwvl0yTfqmEtweqDj3RZzsXUVS7+9p71BuNpa0FwgTGrphNPpldZiKKsdLoRJbzuu+jLNZcc4EATOMXbn0SKXsAzEINPunqmA7twx03SO6dIp11xjMI9y+pR+gi4MrHl4Rx3Q8HzyHFCnOIbnk+cAtvXsccd88izw5lBoIM8p1GggopkQnwPwHAnFhPg88LbuuGiZEJ8D2hQHxYT4LNCCtgQMrRPic4CbAaGbEJ8F4gLL8IT4HACnOAbBzqkprsKhmcufA+ocCcVc/hzwZkCG5/JngTagGO0FM4naApqoLZwJ2JAK7GtoHOcRvxdQqNZKZgI5hUIDeVZjvCYkmuWeOSCn7KjnM3aiHDqRVZY54M2AUCz3zAFuBqR3uWdok6WPaoF/hgGw+3ZaDqwRhTZJHTvhRGpBI9sHXwLUO81OHpxyLNkOvW1QObyWN7Ajtix7ogXLEtv0dEYZkZArZ3dW924ZJifrfc+F7kCiRny89wDNyA71MPZ9L6g/37K7u+UKk5YysHLBwDCgjWwx5RW6+bXfZdNoTfbZlSd9+Ov7/Xuoe45r+Tj7yHSDBxHmNfgUxP0QXGx5t2GnPtsxePyn2UilUKZL8kBpoiztQwF3yBGgDuCF8Mqh8pV02zmW7pKee2XIEj4UcAdKGtlOB/b82zaSUq/AOsDKMJyLYVXCOsTKAcbl0CqBHW5tkkwdziX0sqSK1REPMTyD1cWUXBnsMK/1bn9JzEpwh7ntVutL4laCO8DtdEHt44m6fYTGbz54hBfDrIZ3MDgn8e0TsOPp7jxlDUSqiKkiNKrUsInkllwibQ/TxPJWSSDJlTy74LfAl6ccbIFMOcJL35o62yAX1e6Ugy1kUU+dbkvTTehD14SuYc1waNNCuQc6HfHUXofYsiPL1R/h66Xw7kDORBu9VA7SLop4EzszdYTQmjrRLy/1KnYm6gAC87IIZ4iZaDrTnTziY+m0nVAaIEkytERxAC+LagU2E2GDLDlcFtsCMx3VKAAuQhog2RdJuxc/twnOIDxfrgEy9Nz0L6jV7kHPTf9yWvNu8OzkLzJK6SdAZwTPB/+IL7Arb8XNRPkii7wTO09pX1Rf1wWdh/gFNfHtwBUuL7ZNb8xtgq9kquysbStogTmZC6DcA51t5u0IyRDhIkh3wGYfl18A1yZinhHcRREtMItMMl0U5SZ2kanFi6POtnbdmMe5KL5O217pgZAFH73HjnERrXMHbCbC0at/GV1RC2T2geelFW8ndnbql1TQrbjlLSFnW3jkrB/rhbyZjXJg/favKtLhXQfF83ocWRNe2sZKL4fLxHGWI/Q+lgzj8vJrEN+E5b9eENESYiamM5xc76NJPZtefmnWM2t9bDmm1eqvn4Fr2pY7WXJDTtZl2Eyc57ou2keYbVG0/CaIIhhGl+bWNdR0kVr2sgMs++C9zJxuF2SV5zBKscu8gtjCOOnOxypSJo834dFyZxem9zAsI2ZiOsfhSB9P+kFnIwy9HJIZXLY2a6YT2nWinZiZStRyIxi4wE52Js6bcS9utjLOXp85407MbOPAMzQe9eR06cwJ98Fm43xxbDl5znGZppcn/RpN24j5coiWELOP8S+HZgZXZIx/OWw5lts6B8uXxboMm3OMfzmEK5i5x/iXw7eGmm+MP2+6XZAlnuTD+0ugoXthLbVTy8PUm6lSeTMzbhlaaXNNCSzVHqL0ef0AAujA6MJoVmHz+hFz0qUAmLUbwxsPWLZev8i1JXdSy824zaYNC5uqVAhTLaOT3YFbAtWweQt43TlOlsGxl0AGjIpEcrOGDhFiPFQwp5ud6OfUjpOK4qQzaP2sutfs24hMPX/Uz6VvpqhCZ341n6raz7POU1f4i6jtvFV9rvWcoZLPuIYPVG+aGNYPvMgzvMHw9WBDiiUuAgg9OhMzZeQ0BEmrwRsIV+fMpI8G5YIlhPBmuV7ttrSFWrwxN4sUyLR2sDQlfRH0KLjRFf+zc4hD2pInD8/NKgSU1oBIU9Qz5tNPhq5sf38GT9RNNXl4brYgoLQGRJqynTGffjKUmV0tEz4D+5G2eLPn52aRDJfWBpSmnGdPbJAV96Qjvj92KFiDx2CzbnWS5mMvp/VLy6MdHoW166EPDes43V0T9WAYYdIIFy1npHUCbrpXm4NdDE9akl0NDK8bgjjyTrBtNrHyGMJNEAbQhiAc7JeyxzN+W/1kGNnLCzCLYkiZazVq2iB2aU2Ab8cna9D0BAzeD6UDr62Gt9bv7Pmptm/WG1bCVKtA09qwDq/YVV+ZR42mo8cdLhjtMX61HrsRdF2ge8djCJvXL/Rb0gj16vvzchsj1KrwtGH0g93DgIhZORazAVi6joYrnUy8kMbuQsl7s3OdBFbDYgVaZldJXtUjcLCny+LJx7cEWpD23CoIFW3hkKqndyaJQnXL1f3zK0WDnYcX9BUNUUg3G+qbm/vt336fl+91mCIPcrdaLxFqfyxmzv41rNHHh9ooAWr3XXwy3Xv817BKLyFqs5Q97fb+cq3RxkOkwlyyLXroCFWXS7ZJHx+eyrJdXrAx2ngIVJaLtkUPHZHKctE26ePD1bMk/dKsImKRYIxmdnUweLlQa/TxkRCMXahVegnxB2MXao02HsLB2IXaooeOeDB2oTbp48MfjF2oMdp4CAdjF2qLHjriwdiF2qSPD9McdoutkErde4JBYJlzm6jtMlAndL6lo0KN6QCmxUP0/FwthqBpbVhZFg/xKzOtMa30uBcPfXCFqlWaMFrNvDQB6QPdiIMnGOqrpXmYyyb+1LhVI7S0Ql0U2BZJCgHry7fButsGdK0wFlUoTPZTzKtJqZmkC/BAu1KY7DIo1rBSsGsYZc6O3QWYshST0yQXwrMNMKO3XgJFenaNtuyiXJcKPasFLsqpqdCLhsIh/EcMXaMl63KfLfO35tXAtwDUunGrOute/zh4OK1xLC2GEbLMue94fG6v/vPxbbmyGykMCtsjW+rABP406T2L82CpAbT8xTzFZR9W9pOCbQks6l5f0+hbYzcafWZJk6C0Yhw45t1jy9kR7MfKXu54nsEc2mx8Mtqzm9QSUAQRfLlyNpuOMWK13e3cMt4oIEQz5zz2LvG+AiGm05BttIK6VtovXgHdOmTsHDCJbecXa5bPIDCfQQC7m2Wzebl9wxfwlF0cEMckM1Z6+OwJN9Ao9Bl7wi6zhpbeAtHOLEuznOJT0/xi4eO2R5Tk06Y3xTdIXsw9cfTS7ZrR2QpMFCIG0WuffzoHaEZ2fd6r7XRL8NpfLmD0KWRsAK3EU0vJaCleDXRMDZdho5IMI4CvL7GcsZO1DxJogOulEp0DiGLg0ZPsD9KoAOulkAXzc2NQxkVFYIprWKhZdF66UqUSgnmyKOHqJQBs6+ROcPvbcLtUBtZL4eDqTjx2sqJB/AWqfvAo/Ntvp8pIPcyiCa+fDiq02EGd++gJP4epVKHR0JhtqTTh0dBxvLGvLqVlkiKjJKEH4Hm+RDJ0DGRQST6B0Bo9XQUjqwrMfnq2h5O3k2Tf861FXSD7Y+EkL33w6kfeNHnmhyPidoj9tBIzPAfAnx2dKrSBkcoEl45TDFG6bhXvHmbpWNn8iLQhZCE107agG2U/uWjsyxeGmUSt1ytUYJvwEJ9mWxZNdL1koOEX98EAe3YDmTZ8FITmGRDUsfUTSe7A0H3Pnp2T1bH1ErEdLxp7NnWQQQ6qF7pj4luJ54a9QDUEfo4BSQlWP3w/1OcZkFSRDZIgWX7nyCEHNkgBT66OflMSFYcC2SCJKEAw5sghB9Y/WQpMPOSaG4ESrH74j7MNmWrQhmjMsVEtwRqA/xxY0exqQQkW1YLBfF2pDWB/UnT0Bopr9TO0fQR9boRa4A3SmWvh1LH1b1UKbT0ZS820ZFoBDlIybGuGy1VVZMMkyJxWGKMmI5ytt/UCHaToWOHY2VKpGGW4BgmgF1eb2Y7E2xFSkprgul8GQl2X+lbIvOyWt7OtOQ1wgzFBNlufNCEz3E3QAMi1bc2OzeYuTqrtVg2rgdETCHbaKSWWfwZUV3GDwJrNxEyDQYptiELormZLIcVGQWFWI4o2Hp1ji9bdJHNlUqAbokGWnWdLI0c3RKO0wDxbMjWMQ5TwLnbUsx292RKqIBygY6C/bHu+zXAZ3xAVY7YVJoU2ROAM0H/r5WxZlPBRUfE9e+wb6xnJZAgH6ZD9JLPa69IkVMU4RGnWjTJ1c2w4YDZj7AaJFNsQBc/xQXS1Xox9EQM9kQrCQTok/RAwf4vDSLfhCRiv6dhpvvx6IfMQPgaeM6d1ZyrKZdBMpPHwmLycCLoM0i2gmUmHMZ61hdHFEW8BzkQ+DGcz5dRPNgXKRA5PXl0GuwwpHb35t0fUjU/pwNt8GVVBDpGKkOLgMN/4soRvgApZ0porjxzcIInZzq523DVeJ3Ce7Xg4hTZAABrmea4MMmzDFObb5ubgBkn85oPH2Ta0JXiDRGaz6adJonXjT/t+4tmSKOANEZnTfsoGja49lTUSp/lOOJ6oJhzPj+ZxrgwybEMUHGDMOmyqABwgYzuzDTlSaAME0qdnPlPaRDlEazanhhtUWk8NN+Dv5ot/R0MAOl7wqh/i4xEpBrbtzXbOtwPqAEEXRnroGY9wPods6sRqEIcIWWGkP87mjHqDTAFvgIhnzbbup9CGMtXC2QYpKbQhArM5LtHA33piogHfCFdjp4tloJCho6Ax214kB0dB4nrOJK5pSGRJpubKo4SPksqs53EbIGlJkexTcyeVgRwi5dmvq81yvi1ACd8QlcB6AhHUgWHAcLbhVhPlEK0s39lcCZXwDVAJLBQZmKv9bDdCVQAOkZnv/G9ANfsbnsFsdzhn2IYprHf7GZNI0Q3T2MyYxIaOwm6+0XCBbojGfHc/0O13IAfbgHGebdRVAUhDpnRKb9acajhpqHneozXvgsoRUtCJLDyJNGc6BcIBOkXG4pmyqQAcImM5c2aSoxugkV6CM1ceJXgDROa8CY1y2xk5BGoEs+0ry/joqMy23Srjo6ISznb5vYyP75IqNNYcOjs7zw3pCLhGv+88OY+c7gQFMfo3dMHBhrNbsShodaFlopruFTWhD10TuoY1v5CvybgDNA/xR/iK1FpBcqPbxVBvwuYhH766nvs6v40SnbTLgC/2bClmx3auNDEFuZbbcnGqPd8L5zg4K5VbO1g2on6AAtXIeroIolWwbERxbUaY8Cz1DMPtFrJNwHSEk8NvMyZYAKQlNMfNWRVCtGdYk+dNctvWzBKNtvBq4GSk50bwJQovoy3tB81H/GKanGHgfAa4iM6lHzQdcfRiMLtlsxLHHB8dnXkeDi3xoT8Emjw/1z0oJUoM21DSN0KY+u6MWVUwUtKyfp91e5Hjo6QTBbEx53CsAEhHaO6DeMbR+hOw41nzKQBSTS7SXMjamIBELhBG0Lw6WoGDL4S9cgavTh3KCXi0zsN3SrfdCdwoKCRp6vSKTfvgTIsaQkZuBk4Rtjhc5w3Qw9cDt9phYjftsQO+JDhFSG0HWgduTpinneWQE6K4Z9gJIxCcYNtzTXe1kJU81waHtlyXLS+cO29Ary802xbqK2fo5pmlNWRKLbGUVjKDhhhqBfhmyfeUfu9PLB5Dnba0voJ8dPQzwBmtj5N3AH2mzzqFOt6hBfL08bkEvywU+6Jh7m6v7x7y6ofKhkgITAcuHFOJ9UrStaburtcWoe0flOAZ0JhirFwUn4F9D48gtlFD+h1qGaBd+ebggcB8Ryb+rANqPqLXH0kisQVqS1AzsiC/L1zPhW+XC/T/6BXsNPU3HCNeAOQV8Bhs1gvntN4m/8T/AtvV8rjabfaWs71B70eeZxtnYLk9asNwgR9bWCYkcvN3Fic3Xhhm9Ha1XqwXqwXy6vVqvdwhucjJ+ySaj4swAgb600L/fptVh4V+hd6/2S1X2+tN3jD9AF+I35ufQXT+U2JV1JzqxBxkSiLw7Hx+8Qet8nibCLxOeYJuIcNMikC3XCtaGBQSuqrzGUnDtVYjcknYkytRKjyzQhjFB5lKcMBSV0JlYx75xEIdwk0YGoHl46r0px+08qekYapUNvTdD5ofeL9BI0L/fvP9m4e7+88f797dff27/vD11/d3n/T7T+9//fjh4c3bN//xX7j9crwniNqXt0dgh/D7ZNkustwPCRYUyrz9jyzlUrfzfXvzn8WrD14cGLU3D5GtAxjqOO8OGlNC4Ohpqtojef376pN541IoqD6Br31ufze5gaLxk+kAM3hqlVdOh97ycw/pykMJpPbfElDhc6cGEz5ZBiSegBpU06B5DjoxzWPn4wuVWrvnuayZwI6F/EzH3gxdy20xNL6SoXEkvfXnVHnXU8nZYwe44NThCM2nAnjC8DoeDoBlJ5fhAO9l+CEj1IEbQdcFunc84vRyNK+cTLw6MPwocsjhh3yKZ0L4jxi6RsVGuDY6nhnbKMx9++3ND2mb8Pb+nnz53Ytju+Hb9Nsfv31Dg5Eo8t9q2vPzc9ZZIRpaGGqfk4cWEPs3fvK7tJqT11DYlnxpmeRzbCwSvQtkr9hfxMa7BFRn6HAyDCLAN52KxD99Iw0cif3wJsMQ9fkRvoGBPLX4H/hPDT+Ut3gZuz8RU6UoEX8s8Z/f0zd2A91kd1uXvfjl6wcdRwEoYHGTA+bfFz/alvsIAxyVLWyz8kunvuozRiZZN0AEbO9UU1Cr1gZuZsOGGKtWS/X0p4awxoNRANyQHLfrfgU3qcUGhAH5pP1tPDQjF/4KHTzkgJfjxEMeim2MFPowiCz822yMnaq4hxEwkXdfjsXx/I9AZEl088eOLK/3xM/cYoZaxtJAlpPnv5qlaF5PFseqIb7u4fVoFElm5AwvpGXVLy+FieX148vnZd7dP9w9aO9QPdfu0ikaw0EjW9JFoQ4uGAA2LAjVcmEZpUMKvHJIZO9sNgIyHD/WQeA83QjIiH7PNiLQCnlPAgHtIZmT/YjnZD/8/GWzvv/repuLzSdJdGA4virRcMhNeSUfkCc76mRH1B7IKNtwYkWS8QBSlWj0eLpnVoV0NCbKpjg86taDVYlvD3UjvKKhsiKFcQgCVdX+iJp+VUV68o1AlTOefEsdbMvTfU+Zyc9HdSbHEz6KRFtrVWVpAWVtlpUfvVYgHF9uaQDq6IJRuo1aRIWiXw5AVSubiceTGZarrPO3IU5kpIyEwlpqq6ulDrDsg/eiSroPzgd1IZcTqmoHfMNV1Zz7gSoHR5L10Dq5wFalAYVbIDLOPjBVKYBqHTJUFnWFqG3P1zcUCFc3uFDZKsYqm0WVce6TCVTZ+9n0FPlJZeeCXBVOulAgVSpy6whJzvFLEZ5MJmphhJwj9kvCKWeqqITXgVPKLqaoNeBbGp6mRhEnmVsrpthprVAThhe0SQJ/wzOpi6lFBrm7/Ajoi7pPBt6xFdK3Lr2iQjTOBycRWAHEK7MskxIlIfj0WuymxaXlKwzVTQgcjkAnVxFe3QC2fcC7jJQpSA79idol2chR+oYLcGlPSGmlnE0GnquP8BR98h0Xs7oMARz4HyIYyPsC+s/Q9jn9M5Xg4G1yAgxIEyMuQIABaVdEECQCBBDE/ikAXM1+ISLNUcrz/tEG4blortEIRCdf8dqkUx47PrKdqtjtxYGoLkEYA15C48GRLMkRMclRU1Jk0gSx80o6d+10sIkw9LduxKibdvQInKiXBukFSkGIHwE8tbVblhRcaaQkBRd31BVCIw7Qk0nXEBirPQegFiHiSDZrCUg2a1Ek2QeySCkIqCJLFq7kbjtZyPKb8qRISxP+ygJX5A+WIi7yHqErr1BTcdLQZadReaVBw8D/E+GXiRBAgcos4SXsCjVJgpiyM8xnobpTSAKGIUNYCFmkJGOtbLcPCFEfQN05Vd89DO5/6ngRTz7oBorVQuvIOFKrC8qSxXC9y7SnqP42/Yio+iZ0Y+qljuqbYQSimLp6V961JNg83c+Vegybt+V7wciRhiCCLw6fBDyDDmybugVOw9gkuE7tWMTXlAaoCEmBMAfpqRC8ESADwrLfoPx6CoG8TqkdOmbwVPYJyDIDmLydHHkhbyf/5H49XGdrUNk5GsYlqYpEbI4UELU18EFyYgaHaZNa9UWmtrPyKtM+sNqbDEYqvWecLT6WDNvK6u+Vkq+xv87UtNdepW+bGy/qJ+jCwOIrHPNAPfKvvMewz6v6HtPqVsurIiXEtBOr9iZ9u1d5kWG7UPU9hs1AlRdZ9stUX2TbR1J5l2HHQv09kfL0fMDZELJshKi+SL/NofJeAJxj7PJZKeCsawy7AqrvMa3511+NIHWw2PKqUGPG78D8rRLLinr1RbZN+ZV3WdbaixdxUM3TPeJoJYs6mMKV9MUkdOB5E0PleQ/3ajzvQU59aa/G82rSJ/G9yRJMl17EfRLXe7hP4nmR9ElcL6Z9Es+7uE/ieS/pVHjeJJ0K14sB9eiw8l7A6a5pK83zKn958FcR0sTyvEiaScoXfdTr4KucgJ2NdXGeHYaxS7sAlsCxJCEdL+cSKEkEAGeyIQfjsRmKA9cH8l0AbQhCmH8mG31eyGZ/w8h+XQAuXXi0lmzZ0jKxL8mv+Bc99KGBp3FobUEjPcsBIEVBMs+AP4tLSMfZyb4lMo9F7UU9Qo8QRHEgRZRzpI7ReqQwzd23y0mLUIoQ6VbP5MoxfCZN2PaZIBHz+3Z8slzNCLVqfo+B9B+c7RCvNlFuSSKSjvwkwlx6pesRvguHulsXUyJkJx9cGZ6bjkbCvHndNtOwxMETDPXV0jzwejCnyrV0lUlWmexj0hGKlRWNAtkMsHWSZkChAlXWKcuWibsle5DCYmj1WHllUsnX1EjgJFYmA7Il4Sa5MHR8Oc35ta2qowYsS32zubnf/u13WaTYFU/A+PZ+GsJE7/h8t8tp+CZ6R+JrQQhvluvVbjuNY3fqn47/mG7epX4y9qM6fZf6kdgHKG53Q6h73uM0zt8NYEILjOn+nfqn4z9qBejUr4R/phV9IGmkAssUHfRV8mM2EmYqlS3JRHk6zo4snbwcAi/yDM/WUMeuZT08L+ayrFLAICquaH61WnMsUXKzrRcVHiK3fQb2Y/JT9kma1AywLMHPziEOk+/JP+XIy1BKEfn7M3hKvZT8U468DCKTyGLnbSlzKt6Cm6YMzjdr5t+ok6zjTJR4VyjDyjeHFuMMjaz5V6mGLNeoVKCaAWNqGg4NEOeM9F8VajgznKDjEJ8f1cN5jhTqaV4qqVDRGbimbbkqXYvsj8XrJgp1MC2BcMhnOUBIKd4qy2ddWeLRkfmvSh2M2W0GVWRb54seiTJkZJdc6ZHUaUm7CnUKsnZWnYYzw8lnDvG19k+torz9U6emaP/U6WA5KU0pvrVei6ko7rsIYx9nlMxSVpRT6wPDgDYMZHR+VPo8x7V8nKCAfiMwjzqc2V8pNdwa42tlgC2fB5ZtGI462Q4wlAmHxm8+eITK5J8UGiavgo4K9yQazmClDj45u6pS/G61Vic+/1qVeNwoFNfWStVAGnHIcoyfTXRhG1Hx2AjpEcEsoiy+YjxMxalEUvjdqia/2RuVBX0qJD4NUuYhBnRIHZ5S6JLY/vXqcuiPbzAq8Hzwjxjq+NgPNpkqL0vVyBgKd6kg9x35IMA3LqmmU9alklO6gwf5tA9dE7oGQ4pCGlVZNN1s0yQ2nC1KKG5X4VJRa8+UasjuzSIzbko1SRmWD+iQOrCl0FVqOZXqcuhPZfApkDWC7lKTtpzq3bqqSKnPVVWpK6JUzyi+Xe4S1BdWizalJdaiT8JMG4M2dU5SVjaKp7R26oKqcO8KDd0L84NdpW9EI4Ze4foBmc6BEYuagGR5Jjde1tc1Kl/KkGjJFJnl26lIpC46WonkRF1IvZm9T7DVlMxqgdIlpUWmn8a9pXKFstyMRSmSIRcIpUSW+3soRbJcNtImMk+iVLulmt2ZBqTiO62lCyU3YEuXagtJzapT4uYl2Um9yrf2CYqv+gKRzekH7RJZTvh2CKyaNoEoRroqkeUIcSaQLBsHsR9VaAP0RHKnpIue0p+sIIrZ27122WGaFrn8g7jk1BKNH1iTug1psMTBV29yz+eiK9+qkJneGS9FtNWUHaFQJ72SnuL+2iE12Sx01SqMhUgjUzdfXeBYBsliHrCGrQx6fM9jWMRlFMw86cQgP3UbNaIjEJzoDxz3Cq/7pBQPbDg6naGLfccxjDwvOpdvmIgt29ROhqElbdOVs9lopZwNxbUZAyka+pRkWVTzmyyQYPTJGjLKsEyrLtQEPt1Ozz7ZmbU7ZfcbHO+Q0KKzFZg4ezgagKXLVxhzcitx+nk4WTW9qMAa2ktPLyt0VzJlPaNR6NCOPGqBB+SY+6HN5/TSrNNwoll6aSSIpFoZo5eJKyjNRTvUEg3gQNuW5y6GIc2Axhmg/9ZLufJ8zx7aC8wgkXqXN71MqQ5jDK8u0ssieRKv1ouhbZYMEsnxKGD+FodoMAdPwHjVkzzfSlUcA8/BE3hqlOCZQaIh0aZOSRj7MMA3b6lUFIZDATOn4Jfd8layZLlFGkYALwFbjrTuyohQUB8MJryllkdzbw6DMGnxh3mW1glAwxw6W8EiS56DpLv75IkbyiNLL4rqwAu9OJzNSpawk7zw4PxoHqXJwvtAZdZM25FWmbJdcHLDDGdoRxiDpJ00UcmA9hAfj3iJ1UYRtCzRLuomQxSQw0hawbgW6sUen2WJ8yxpReIPZkCmFzU0V80gyQhXQ9mImKRJ8zss7FqasHT2RrY8qZFILpTigBm9UDS0Wm2W8oqFLNZDcnwhlFZtceQsk3VgoepmrvbSxqmBvCAFb7KXKGv4PigWaRuJsnbyWhaJA54Qr/4D4yyt2hKBZIIgjK1IXsBO5HreoyUVaWTh/laWxOgcQGAOHxmmF2g5EqXRZdOnFidzdIxl6UYgza1TedJKNpEXCg8yUMsucYYUS5MzF1VIyuY+cF5sHbo4eapw0NeUns6GMGws51eCd9X5wKI7Cc+vJnx1PfdVfFBVUpDt8Sa74UIZrWmLcKZDKzwKUIzkWJH1JBU91Y04bAJljF1LAlkOaXHJdSP4EoVqnKOuRJmT1BUpcRYkORAOWEvy5ExmlwTKGpCVROZHBGTKtH6XWi5hFMSGzEosu4WnOoDaKZBcIRG8asMHTYdF2NbJpTjoNygoWY6mTXgyLI6sR9PczUcrSjIyx+OOXpqS9ABwz6W1S0N0n0BoDSYqGxZbWsqXZ0NXd2JhKekStIxuNheZ8HwOAPeSRC5KqH8upJTX4gQre0WYjqVIhSfNPYyIu3PJRCT37coCBA2/SEU2nPqAUp6cCpoueem+ZwvztB2Pf40gE+KYIovRJSkyaqHjh4KRclmS0HpgWRCezuGPoMqSUABqCPuQD0yKrfnDYh6l1TgkSkbx+49Ce+5yMVkYLdgAV5ceRIWFIO/8bGv4xDGVQFnA8EPSnCHAeZzsSD9DG+/6kSFOFrT6rLRcwUmxSpCUdIeS7IcFOtbgrcNUctDn1UZaX1hIpMgXOiitmHUXrBBkkpfXMdBQNoygeXW0AucZBPDKwXK1o3UmW7/R3xIl4g3fWCIj4RaJ+UZ++BJpyXkCLbSQNM+1wSHUziFMDw7LVJYNtaOjQ06bmvDI7AYs8svzK/+JlKDRV2zDb2/efnvzgx94v0Ejent/T7787sWx3fBt+u2P3759e3OOIv+tpj0/Py+QaZBVFihUQU6sfU4eWkA8/sVPfpfOeZLXEMDkS8skn2NjkehdhDCK/UV+xvmBfDx4XpTs3r8q9vGbxmFxMgwixjeditw/ffvmfvfdD4QruWjpOx/n6QwS7Yv/gf/U8EM/aDWOfyKWTrEiK2CJ//z+v769CaDjPUETfXUEdgiLhz68EIOG6Jf/+M/i6wcvDozkW/RdF4HQ9g8zsvs7EmemMj57YfQXvCBz6fafjXlRXQaxjZ0avXEK/9uukuz6r+aw395kV++iBsLQcXphqC2MwMjmiNA/Z9RqxEb2/tR2/8833795uLv//PHu3d3Xv+sPX399f/dJ//z+/uHN2zc//BlZ5Nu379K1/h+/vVktlt/eoG+ga3g4SkJf/fr156ubb2/+jHQipalO9IgLHPhjG/V3SYn0Msc6kCgUuUavDwb6G0nKRL8hmtAD6L8fjp6N3ivUJcVdeSZ70kLFnj93iMpH8oqJRPQE8iKcOxaiokusjr+0LfeRfENcMzHxoALsG7pxlC84Ce1lS25LNqDAMmHt4kNFOkjHgZhgn8Gnoc8gMKGLfFaF3SrX+qgghMSawZMiUyXuFD6rL+7GlcPKNfpKiiPMKrd6e6U3DytqonAma3xMJ4zQuNfR05UfyRWkPGulyIFrSWLUqGkcQFdb+Pn9XePQSbILjFBCOOGOei1ndd1XOtejWHqWnUZIyQ9aEiGVv0onND6D6Iw+xoGF9UaxaXlvs5hRy+KoRFYeS5JP36mJC79CB0+tQEWRYTpAGA4Nv3z9oL/LplPC1PB5dF+YvVkWdN1GKlk3QARs7yRbQUtCM0OqBqvm/3pqWclEGmpIckOykqJKIemn1HLCKoqdmMpUkSYhwN8tbJNPLm/Lkdez0ZqO9IF7GAET1amp2w9clqkGC89O/Gsbn2Ximdv2HfP4rWVRezWbrW95tuON96QB7Xy+462HZJ3jIziEA692CPjw85fN+v6v6y3V610oyJQYg4T2huo1jKCTJAR00oSA35pxRsMLUdkUyyaJGbWSXbScopbg1NoUNds2NuwRCJAjjgG+TRM9+pYqzljYd0mDIFraOX6wXS2Pq91mbznbm7Q7kmi2FK7WrU+w6HPBOjAcfwQCuR55wGE4Cu5EjTTYhzgAzhjAc0UyoUfGSNATRdKgG0kaYNXAUzXSYGcJkVXjzvTIA470pwftlGMvVMmD7wAkNzQCy4+SHY3KWTQ0yiPjJztflVNI9UgDDseptFBypYVxCJITsMqR55qkgT+GgTFKtc0VSYN+8o1glNYyVyQRujWK0TM9UoHr+Aa+sdDnyqRROB9H8vhckUToLyMhf5EL3FqPUlFTNfJgg3HCsUyPPOB5qhHl0HNN0sDjvcoGcMdAX1IlDb6NQrsxsGd6pAJ/OYBRwt+yLukE8DZnyx1nuqBNpzxCEJ8jHKdAClXy4I/V09rSe1p7pJ7Wlt3TOsCyD97LGNhLquTB98H5MNKEWVmXPALhKBFDqkYabN9wRwnpMz3ygAejNPOpGpmwkytF7bHgl9VJoxEaAYiMs59cKq6aRVWbPBJwxEazokwehXFmzkLJM2chir7z/ZRqkeeaZIIfaXmk0CQN/GhxpfyoMh4trIzlx5WjTRXLnyl+MsEo3p7pkQb82fRGaWMyPaLAnXSfokLMZRWim0rq+1SUoW7TpGRPCdWjAw8N/dw8nIUPy7LurLJcg3JHVX0r7MHia4YSnNnNbakUmlJo2+5r4gtGQRhaR8vIEx4KQuqQygXRUoOxUyyfHWF6U5mg4TIxfCAQFcjZs1VhFIJ4vSrLbiTsSJkgbiA++o4vympAyUXxggn4+pM6kIC6z2iCwEePY77xbhVGIagfCF1D3thRG/A2qqnv8uyqTAmmN5AWgviLu3ypsCCcujjO4sdrLbYdSgBUFiXkAqzddLGHm7WrDqGB6EWvfDugwzNg2vtcsX2WBfYMuExfcNYyEvieBa0qliESa0MHDEMRwJJkbowhlA6uEMmNCh9STa/ikImsKlYGOp4WnwIdbUfEEPnX6x006PqCVgugl6UVDJKlpfK4SwS/L6soMjwqyqDpRqlWPc3wLIVBm2COjq0iRnJt7JAtijK5/FAJyFy0KEbe3f5UJc0XwbYQVYIwFy3JG5WAZGyCe1BG3iN0FRV2IVsYZZbxXgHITDQnRiMwVnLbnFwiP6LNWjaiRKIQIpnFl0sUKjXJiFYya6SSDqKQrWLojkeJsZvOqPGNtPKjufxxXyWBlqgZK5S0XKzWUCIUqJfzfZFprzFQl3TJAS9anehszbbs0GtrYNsHkCQaH8HaJW3qY/YKJrkEW8WraE6Si314JgNJJrrkyqUshbgI/0SU1iKVs60vSxEsmw5sioqE5JTkatiPNgjPYo16fucFkSXeRgZQI5K0duFCrUxNnHAF7MM6SoOSoZFi9rpA3iAOr4fIwpMJ48TiAEtCt51iyYRxYvFBEMozTC6NE00AQ8i3KtOGJpcm4jMyqmNZGCeW5AYEaWgKcUIlJQtOLk3Ii2WhyaVxosmbK1mAygI5McX+KUBCpUEqyeNFJCGiKeAoDGSAb/EGlqT3PQLOHWIlogiD1hDIaXhyFxTe1yILVEWgSHuic2emaEFVlcgBC4/H0mGLXqRCkwGvWzKn9XK3SNou4X6i4W4lucIQw8gLwEl+lSgLVjOg6cjKTsW/kgFVoMHDUrSqQCUDapxNm3s8jV8WHkljIVpFHO8QOssMLhlSJlIElvCYvmYlRe6QVH++4fzpYIsN5pEA3YhR7Xb0CJyEp7sTLhqSqnVIFxrOY3lYJRAeyLQALQQLY0xbdPkYC8GyMArWkW6MohPEpSKRj7EQLIyx7N/ygdakS5tgkrwjEMHmyYlK0k9n+eU59wRS7lNtLUNynWIJAleNTblrFUn5ptG6eP7dd3jHfFkavmuOy+P6AHfoEEDdFKiHfMvi9IYuaVG9N4728Amd/8krzmyvel28PP+TDrZF/ljtXUfhpqnyJ22gslseyF3MItWmSiarN3XxIjU9lUXyrSlDmkmfe8WuGFakqtSskVbsunhZ5aYMKUsWPpFyS660kFZ0yUnLlxNnnvAO0yQg6+VY1TWPtg9fE8LX8EmqQOV7SiQ4JxZX88yaBgk1Kb9nSiVi9vTF/Xh5E89SwmVOONuPljsLJCVc9uyP/Xi5c2lR4mXJoSXSvEoKZ4qb2AQHA2WzVAOFugqJ9UQx6EKDzNqiGHRJhcw6oxi1zYZaYX9L1lqC2I/EhhusvW59QbbnIhzKQjSc0Ap1F9lYf7KCKBacpWjYhbR+AJ+GbVWkJBlGl7c2wCmg2qVm5i29pdw42YwVt3WoS1XoFPkQgX51E7dK1StAp5kBqWIQKoOqqKwAmgpEvKd2a6r5in5CTRTeMxE8JTu1VVPoUio0+de43Jb7iEQvlR5FEkslgBEITpwbIpmKoqxJov2F2lIqw4u2ojU7+J5nK3OaAWWSaYyDX7rHn0Zpego9c5+hVVeh0rBNaX1K7awadUmPzN4DtYrQjdLrxKPAExsjtBKh0znXFfV39w93D6zr6e+4zwWxXxXZOuoTSvdFKGuYQ57tsCmVP8MOEZXebCsXX0koN7zod+KV8IVvu0sLtqpEQbudOLOmdNrsRJ82pR0WycblbDbSYJUFcsNy/FgHgfPEdz1qC6yKwLk2VlRHRIX2wUqfhRbZtpoe9kz2h+aTiqy7Viddm87A8nhphX6+FFGSOPGcBV5pnsatuHc+pCbF72cOdSn7HLh3DZQ5p14kfY+A5HYOOmbwxNzMOWD4LRUOmSjm8kdCVEsEEIcsZM3NH+sWW2d3fIiuYySUhS4oqZiR+HiOTmuKH2/lIi1NKZQKWRM3+1TJwyU5XS2jIO+Bv8SYpbS+kOmo3yQtoG0dmLO+8uUSho4ODMfnbMAQTtJylaRwHCZCbyf3sguDyMXwocCXrAtjSIXwITAPfOfOKghSIXwIoAwbQBEbpHdPi4PI5fDhSC5jFoaRi+FFwRnu1kAwBLoNDPi2W2EIqRBOBPjeWnEIqRQ+DOQaVGEMmRRODOnlmeIwCkF8SPC9gMIoUiF8CDwfyOi4cjF8KMg9g8IgMimcGAK+Q6VVCAFvYmL0ciCj1whEeo3kzh5xEIUcPhyS6qdg7ZTUhQr2oOSCLWEQmRQ+DOSuLGEMmRQVZ9M5r1bKYm6+MRHmRgZDhRSRyF0YRC6GM3I/WxIskUnhHz2IQ6Dfwd+KgKzjcR7nrgMpyeLAgxeHpVilKojPMgKXRlXrisidUcTNeSe5KnWFN9cONiP/rVVV/xC5tAp39sA5xq6ElqMkiLOXEliuriBhXKJuKxvOhH21kuHO1Je+rZ+gCwNLQuHUpfHPighDSYXwz4oII2A4ndU5KyIOgum+1i4c0rqZhjiRuRphNLkYgbkaCSAYFuha52qEIaRCBOZqxCEA+pOXHXM1whgyKWJzNeIwINPd1u1zNcIoUiHcCKQ1GVVZInNHwlByMQJzR8IgMin8c0fiEAKBiDSQ0bcGIn1rKANBKITgNTSOEoKcQo7QLJoMHKkcERzy4tCmPJHZPWE4gu25pFBQMBIk83Lig6ZUisDsnjCGTIrQ7B7rKr+PPNE/wwAMZZeUeBc7TtnFOwVR4M12kpWkcc0PEQHcMXM7HrrgeezrmnNkPBPRJaLptsWyuFF9lvJq4eZ7yc3ingtdzkQ3+MzMAZqRHeph7PteQCenQxpDKuTegrVyUMAwoI3KiPsOouLq2ZKttCbtLIVyn3L6TW6DvDzHtXx8wpUzUhWhVdMtgZUfgmlKqk2x0q2IQntcO+yXEeQ830hptezEY6FLtOAh922+bKAhy+W+skqWbVflUMkqrQ/Z2cdCl2DJInPrwFbcMJFMKIUiQciG4YwDuaRIFLIDjJEwlzSJV/rkSKqjvOcibl1XJwr/DFbj2LysSRz0ercfDXZJlzjw3Wo9GvCSLkHgp7Fak5O01gQav/ngEY4Du6ZMOIIkcdwTsGPOe3RYu8qqOiVhhVD2qgQhw+WlXYJkhKdWCQxJPCc35CuE57lcWvRJGqSkUoVSuXDx4Mnn0skE9YrpngjdhD50TegaluxQvIVPj145rFJjHWLLjixXf4Svo5DqUCuVExJaDmXGY9VULJ0XanMsoexgvLyqiqXyApDzolo+Npk6qRwczm3CfBQc+u3E1AzICdMo5ryjl49HRadUNgaZbx6RSqFQDo8oAG7ogwDpHp9Tr3Jl/M6894SLszsz3yLOyG2sNq5HtTJuI7V93ZrlMxu/q+3XLoeh54N/xGN3Wa1KpfIZv7A6Fasop/Ga/S69KliN1SC2a7245Y22Ea7U6ZuS9bITK60aFY6pVfPp0St3zuMISVCrnlGHTvmjsxGKpqZOxWhgPBaFQpUzAOPxaSpWOWMzLi+5q16Ncfp4ZBz6bYjDDNJ+E59Lw0U+SuvcplMqm+jVH6efqeuTP0IZtWA6FcvnNVoRtSqd3/oU27WiXVKk7J0qsMgM3BsXeFbViC94FvL0OLJ4s/KzYs91SSUgfyzYR0HiCLAsFuKs6v7rWCxK6qTSkD1d2cdB2vxkWai6eZM+KgomTeriz8A1EQ++pCmclMo6pRJSsi7Tx0buokxZMogiGEajeltNpZx4JRPuAMs+eC8quXTpu7gJrHK3LjG6a1wjXVUj1X1NeLRcucFpD/yyOqk0pEfYfSTkjYAasdVIDDJdcpsOFVOEdRadCqWWBbmW0AV2spdnpEJpKJVbOpn40UqnrFDugOEMjUc9OcYzVuHUdcolNC4VRSSkz0f3kpA3Gd02rhqJRUmd/GHcSBwyXSqHcSNRUbAi0DmkGpFSWaeiYdxIbCoKlQ3jRiJTU6lmGDdWZ1/SN7/5ZrKqDA3dCwezOvQKkrbrIcUidUmgJLe0ll7SJGU/QCpPP4AAOjAak0NV53ReJjl5QwDMwTu7Wl6ybH34OpKOtxmui+lwBR0D4Cp6QlfL8GcXwJQkMhRsKyrdOfJlSupFlkkVRpekqtVhEHg4FDc5h8v9YNuVCGPnn2Xph8uzVNmOUGgKoh8k32RDDafkaiNcZxRUGCm1RX1VUVFPlFQSSTVEVfXgqhsi0ZwfeJFneEKB3AFZRnz2n1BHomRYM2OlIXlaTbZg4KYMJh9GCWs3EMKb5Xq128oqxEKiVCMVYrV2TTJKVj12IeDixf3sHGLhGy0z+xNhUg1FJGoN+TKKVhVYXqTiZfn7M3iS1vQSYVLNQyRqDfkyylIVWF6kEpKXWSZ8BvajrOLM5Ek1UiZUa9Mio1zVohaAPNLkGr6cRyQUg8dgs+ZwoTYxL6f1C7OoXp/E7PTQh4Z15Mx3XI+akUCNgNVyyFqnNlYH7XbTcYjIYcHeNI3j6iCOvBNkmzeriUCWIzYKoA1BKNwTZuKyEtjqJ8PIhC+AeCmnlLUabm1Q8ezaKd+OT5ZQ2RHCeOeMDjz2Zqajgcnkce23q3cfhKJWkau1KRJfOauKlNH1UWEfOcIxeIYd9UbDjaDrAt07HkPIkh2ZtgCMUK/qkOhKRqhVZWvDqqX0WQNq5DkcM8Mx+rMOVzqZeK1MjQslsuW6TiKzYdBClRJXScTrETjYnDnN+AiVNI7AS2oNoOI1s0Cuo44UBEg6Nt1ydf/8KqEdzyMdufUPmTbdkKdvbu63f/tdSSBQsUUer2+1XhRSvbiYPpwB3T4wUlkHqMtw8dFZ73EGtHvRSOVd9qfb+xk4dQZCtU9PRrYHi3KPnox0HxhV/rxdzsCfcxCK/Xk6sj1YVPvzdKT7wChrn5MeQMUQnj3qkDXlOdjRT0G3D8xIUccUtHvRqI06pnbqDMQoUcdMXFoJ586Ofi4OrYR1o8Of2J9zEKNEHfPwZzWcOzv6mfgzN2vuqc5WMyHAuvcEg8AypU7lddmmU++Yiw4FONMBUpeZ8LXpKoyI5GptimQuM/FeHM+FfeRlJh9coXqXpvGc71QlMY8PdCMOnmCor5bmQcq+8bRMqlZoaae69MufbS+UrCcmueYlKachxkAKuMlqv8QmpGaNLm2C7UhhzRHw1xRJgN6wiDJv7NImyf7JIYYxSLRpk+xEyvHLg95oWsbzKCrVsumN52tUqqeJHUP4jxi6BlOKzWHz5lKVxJG5dK1b6eUd++3+gflkU8s5phhGnhedWc8PA9+3PWBSuodg7tWWg+S5fuwJOjCBz5FCrziLlFpBy8Xmmeb6FKk+qcaWLqBZ72rYfYupJeuzTpqMolWBwBncHnPLRd6vSHW54kkDU2Qn6cngySPROMQfRPDlytlsuId59d6Dc1Nyj0+gwslLimk/cp8PEPtryIhaYQOttDO5opFzdMg5fJp657r6TuoMAvMZBN1e0niD6h7aFvfGM5FxQGo1mY3Tw+ehPBkdsgS7KxS2Ms0+ZibS0gTt7VSyxK6p8Ll3RhgmQyNOaYO0I0qFS7OB+mqAI1P6KhCdrcBEI4QgemWtB+kV1HyOT45pBEM6ewoesM27Y6toJbJail5LgWiAeT69ige5URgBfLuB5TAljx5E1pDMjTE6BxCNdNhSdQ/iq0jlxpaNxaRCKwsVRsZ8nwE1PI7bC+oYQ6AAXkkoNzJgWyeX9Z6h4dpalsqN7eDqTsyU9WYQWCGSHxUKFvdbrqy4w/CasvlxoiKIHdRDsmVZHMZYlSuKT40dm7JFcToe08VvtBBTsRLQ6QF4VoQwEy0JJSqXJxBabFkNGOFWdPDjtj2cvJmkDFbkqV0a+COdJOF08OpHHkeC6OF4p10+P96E+3MAfLk4q3IFIkfW+0UpQkb2C0T74lndcny5btkuXhZaFRWpWwU/6ogpK/kwxIgx73gNjwkP8UmN9ZqiuVFCwy9uJAC23MCyTbggUgVdUV0wP8Ikzbvue7bc8q4L5kZoO17ENL8zCC2XyI3JMfEth1JBFSJFUEnv40oy+XH5Iccd2sPQKmKF0JEsm9LB5VKFsOG5FbbLK6jAFWKF0EUBMOQ2bRWp/PMhwMRxr1RkJZn8uB7VdK81uSL4pLchJZkCuJ4DK5LraSWZwvNuikq1TTp/nl0kDUU0+hnaPgzk9qktsoVwKjFnXTD/foLQ1pOAVoUtW6ULYTVsS/YEbFWsGDoyjg5jVBdDNQXfq0UIu2OFTDnrqKBmQoWQIaGrjZrRR7t4CWhZ77RjQMp+c10N5ctueavGOxuShXqjbN4sqZuyl4Ma0kfYHGDHJsvOH6F16h7jArbcRp3mTBnln4GUWyJBYMkZkDbgpYJF8YXuSg2+VLAEfPJCzDaQHMFmK9JkCU8JzEK0KEayVKIGYy5aFGNpYUQN0poCUbx4byHqJ46eGrQV8YJYDfSXbStqkcrCRXEaapw0lSuK7gzQf+ulGogl4VJw+p7NdDspI9JMvDBWvht6GdBKvY5XYfskrWUyHCBnENRAmAoWxec5Poiu1gumfMD0KCvihbGSNAfA/C0OI92GJ2C8plG3IvC9+lSwOQaeI239hIpPWaNURnhIRIQnikZg1KJROqMwxrNOMBqXVYtWqczCUM6wvZ9JqkUqcjxBMAL0TI0c7IoruLTaXNparQhuVYMo4ijQzeCgKHYpCRfESSawlYDMJQsjVDOfw3xVYzu6s5qRSSpXEB00zLMSeJlgcXyKmp9csjDC33zwqKbNKckWRilnKbiJkHE5uB1dssdIDcJCtihKaZtLGhjZN5i0IjwpmgU5SZkFOT+aRyXwMsGi+NAgVV2XXJEuiNR21PR4qVxBdKk0lXMzTRWimOUc2WjgZDyy0YFtpwjcTgY66HjBq36Ij0cY6MC2PTVTSB16BNG7aJgaesYjlLQ1tY66Jl8UrYVGd49yzu40kBayBVF6lprKlMoVzbIF1fSRqVxRdHJ2OjbAybiL1H80whVTqisGfJloCRjVtJa5ZAkIr5UhvJaBMDtrrQRkSbgknOrmfBoaZCEmh7GVIs40iCL27NfVZqmoSpWEi+IMrCcQQR0YBgzVdOVNFaKYs1P5StCWhAviDCzUt5mrvZrl64p0UaSK5ooCKTNF4Rmo2TmVCRbHt97tVSFMRYtj3KhCuJGDb6coRipEi2JUtH4mZ8WMbPEGxllNj16RLgNpaTO6OsA1JTJwe96jpdDEuXgJWCMLj5+VYS3EC2It0iepgFqRLorUcpTBzEULYkwzICsBWZItiFLZir6kNXxyJMEI1DT4ZeFycKqp5WXhUnCGapaBysLHTOmNxgqiZyoUbGxDqDR5+9eS4y7pBhkQo39DF186LXeqssDcpUoqj3QLjQl96JrQNSzJQUiTTodGFawe4SuCZQVJsvtxeDV1qmAWvrqe+yp5Da+TU1nbPE8uYOhyTy0kdiA3b1kuTi7he6H0EL1k8XZNcln4AQqtIutJPYuqJrkscA1DnQ+eSpMd3bUwaWqTwybZKa4KfSFdFlrpC/EVtLJOSCTykmzOMhPNtIBuKJGM3Y3gSxSO0PL0a1TDapw6PKxVDTv17Wy/RjmskOBA7mR4iUAuXA5WBacTSmDlnUJI5ClZHi3hlbhCmkoMYepyqiBXFEjCbP2urgLmwiVhjYLYUBYNFNLloFU6nJI8bnoCdqwObCFdyWyLjGskMuPUL3sI0AAPmldHK3DwFRhXDvflDSIJOY7WWfySIbabU3p8BqERSpPSNCrOmKIhseQelVQ8s2Pz3pIqdLnKgJlEKlSPmfBVK6l45WaSXRE7zJ71xiLVBIVL4tUkAsEJssvpkBZatoXiTxsc2NPp9Ao+hywpfrrFVlcBbQvFGLIrd35pJCofLTGvVrKLhqhohWZWh+Z0QGkvq6xQHWXPnuKptbSjo6OfAU6ddxTr+vvKPAsH6spEV1ZTcVIGCSz4+UYNM74bru2r2m4vCEwHLhyz38T4pbfaryEMQu0QBB4aqZy0B5yo3jKs6PWBlID2tNOfveAx9IEBtYPnRcn1flfFJZCmcdBKKstG/iEtjc8gOjeK1g+836CBm5ZMpY5KW18v17vFfrEqivQ9fLKQ8oekCfqIm6APP3/ZrO//ut5qd1ndkqd34A5MFRST+TZV0otiUyud0IhdyyAzUYp1kVPSinWg5iZUbjTgW4o1hNBAQvD9d/LVIPuQ2mmQXGAOcMFJXTVpV0YGSvKVvbt/uHvQ3nkBVNDI0N/RqIJaqpRUIdVlZZLWeyzPSLVZrhWpUgUdM3jSTAfgv0bSoYVrPbROLsBZPlWpU9sJQQePhtU69Mm3lNUZHwZkuymwVfswyZQbxH40VqVpKlTUpPYy1ACeTVChNOn9kstuHd9zoRvhD9lh6TD2fS+I0jZ4BhCQYBjiOY0Jkch1uaHZ5zFU5RfyqvPr9Cz2SNW2pk1Zne3wGHySKm13FRENAB6BBsCyddx3JP3TCIpKI0CpA8shdRaE8Ga5Xu22Y2p9dg6xkqiiS+Hvz+BpDLsaZ8vX4DHYrJM/X07rlzF5hpYJn4H9OIZOOz5ZbvKZ3KcCvFGoJmqNUAOoR3ddoHvHo6Kea4gx2dqm411659cwL/BRalJuhZOJW8gp2KOhwnhqfXCFApX0sMgoTUebXrVl3NHtqRrIMq4mjqy5Prs+ZpxhoUADGroXtg68HGAE3nt4xAN+POeYT4LnM8Q/bVfLn1e7zf7ufntD+/bDR/3dp/cf0B/3nz/98uGXr/rD3x++frgn0+dkewSm+IrsVB+ydIv8oN//9MtPf/3wBUn95ee7v+o/3338UBH4//0j9qL/dYhQ8w1DHeeqDKMAAkdPE+0fT4tz8gyt0r98+vT146ef3iOlP33+nPyronLFIenh18+fP335io1z/+svd+9++nr36RdhqR9++ekvNXtwgfuArPtef/iKLM0nDJX9l5/uf/71l3f6+7sHflA6BvHla+VlB1j1AHbo/V8/6+8+fvjpi/6XhwdOQsR19V8+YYFf797p9x/uP335O7d1ajXj3cdP7/7/zLcrQivTtEwKctk/ff3p46e/6p+/fHhAn/lBvr//6f2Xf6+gS2bX+EX+9fPdp4pAPPvEL+5vPxHi97WqhNcwWwc+jKIbaLFgMcR3v3z98OXLr5+/thZ+Y46HVhGZd9d/+XfkqP9+h/z/p4/8b+p/+0BahY6m1nBCK9RdNJrWn6wgivHtVGwN7P1fPrz/+vGhu0m3o/9Vml3JzgT8iVX+54ef9Hdf/v756ydU3+4YqkKbgB6s5SuwWLGShvPuo/7x7i/6/a8fv959/vLp66d3nz5mPUZF25JV7K9f0R/vHvS/vscuqP/ts/75J/39X6p98kpU7MdWsXxSkaDU1okbtnlGEcL7gMvk9TjlQ2ttLAJXgYb+05eqwxheUA8FBw2zQYHInayu5zPq7fVPD7iFKAnM48Wa4HQC8Odks4T8TRBcGwrI+T7tZBgasmYEX66czUYLoA1BCHHEnz+5qA/wJqPTMUjDJ3pP0E3mWdF3JRLkcz5c0xHb7NcBVnn+3nrc3/oY1UP1gL31IddDwX3tQVRy9ic/dUn84Q7vqim+XcTGAn8yziTIQw955Pu+xxaGH9erVOoEY2g/1rQf/afdVVifwFCjGnlapIODVQtKgvoWIhrteLyIyi/oV549tSBDTYhaWxNWtKORb709U6AdP+FYv6d7ZMpttPU7j3qywWtAefJM+teDEVh+VFH9h2yYXlRi/CRuThb2CCVyjF2D7HxARRMlk0qjl4sJIiBVP0PBuMBFARduRqdg7jlWpB8D1PTpvkfi9glAuPj4nAH9qYof6Q+iyBq54FFdgwGI4D3wSQ80Pm9Dx9e3mKThLXdEq/pkmQrdLy8d2v/n/1xdq9f/DALXck/hAtj2BKbP1ZNzo1MC8KEJ3MgyqtFAsmF4vEJAfTK58SGcAkZyIb0Nn2DVFUx4BLFdX9JqB+CAR0j6TBA4CxS0LrLDKVUEHY81gsErB33zI2NIKIghOsfOoYYi/U698no8euWgb35Mo9Irc7UfBURrZIqg4O+v0Pc/UkepDRVFyzeIpni0q4m+CiPzR9p2uke+7zOA8f3uVjsBRN10S4bU1oFfHV3vKvl2EkAdEQ2BVf5tPF/KAg69axCEGh2Hsr2VaK+RYLFYKuuX9HpwcPV/yDfjGkgtGi67NKOWq/+TfjeRbZQhYrFP5/j+6pNwTWe1jEosLDbpHltfHfFvV8Vv4xpoNGAs1uqfDbk6Zr9PZrXRATLVv/7ZjKsjfuCKPHCVPzBytRwfIlNt7RgKXdU3x6uvnpKRtM/MdDzWPV3KP0sqiIjMEzZmCa/Q6Aga4Y/41wX55xhY8pAt+aw7wK+i+r+pvG/fXd0D/8c//NunX79+/vWr/v7uyx+1P/zb5y+f/veHd19/+en+wx8X5GUKzMm2soVlwkU6ZV2Hm54A8/xqh0dWn5zTegu2q+UR7weznMZ+MDE7WWFbJhIi9KMVRrngIjaxv7+6eg6QbVBjAKFOTFX60iG3uTW+Ntq/DmD2fYXUIAo8FrEjj/EtovhkdLXwWmFKBgOfvTC6PAuzkUXt2yK0cCIN4sWhtVkn7Z4ZLZIlepOsCZO1ssXJjRd5jTuA9AB/ySYlccWzi+QB1CgdbXBqy2Qytc1UeiV6E48IroLnF+SeJwe6kZB7cpQY6roYyix9Oiu1/y4z8TLrDCsktCkIq3VyvQCaV/+IgW0dLRiErKSREHyg94rktK1vo1Fk6aEwQbDR/tcysVRj8TT6eSBM1exXthegRgQbfeFFZxjYiN7lmV+Jhw++35rPqg+lA8MQld6VDd1TdP6xvk9whH6GyU3Kz/+3o1yqo1ggWMBnn/RtXY3u3Qc87/kpW2Bgso1pgRM5CB4g0OiXz2B5sxYFjMHiL9J9b5kXPu0W28Wqjr7nhdRtgWmS7aHAxrsdZ8KzEXWAMITOQUqf+II+5OKunq3ofEWmU+Y4EmEVZ1iBEdsgyK9PeeXbDDEfRi4KiszGRA39VgaRMYcEGsX4haFofsgO+5FP3/3w5xfHxo8m5zXRw6vFkryMpHj4xjb01a9ff766+fbmz4mAbEon34cbGwvHM2NUo0IYxf7iHTkJ8zl57DOy8V8I8K49zAuycRiJQ4J9GESvDwb6+0d8LW46d1QuidqdLl0yQ9tPNkikl2nkVkBfZXNiZrvX+ggxMfVDBP0//eHf8MEegKwa/BFjzH5E/04Oofzh31KceLos/ecvCN0fCYb0oAoaul2hbhN9HZG5tuTCGNMK3mZCyDfoiz8mX6BiqsAYqejSfTQPMIrIbh/+MtPUgZToWQpRxkaKU5bj1/KVptPbbf1T/VHkiWR3StSd3bRWrxZGYGQHXYzA4KtJWXfXnx2z6tVvvn/zcHf/+ePdu7uvf9cfvv76/u6T/vnLp88fvny9+/Dw5u2b//r25n222+vtN/Tx27c3IXiCqJ54xuO/g8DC15WF+Ou3+A/8AP4/1ML6FnrKfPzopbkP0x/eZv/oOEyR/fx99g98BPuT33y/Y/o6/fWfyR9ITGezNTajDNI/kdkTYXh/a4is/B/IzHnpIoG4dL/PPZMcIsdY01RIIU5Bm+d00+3jS/lmHfSeF1gnC4WB+Yvk27S6oS9W3xNZEXRxqa72683+9nqz+uf3rDAqyTVEMFytV6v9brO7WTKCSE6sCqm+vl3u19vbDTv9ZCkufBYy/3672iAHvhYyvxHq1XQjIojWq+12t9stdzsRSKWzezxOuVlfI3/YiGFAZknyjwg5yGq/v1nd7q/XrM5ZwRLCf8Sof0su8+Gvq/vNene75EBSbjKgEwuh2N7crJfofxyFU4ZxFmy51ltki9vra2oY2SJ10UVrjb6XwxrL6/31brVmRVGzBkkNEC64IOyvr283O+Qb7Bis2klsPf2Js65s91vUn+yW16xIahsHeKrp9fUe6V7vG6rJILNFt1ie7QcvDtCPSc4TPQ9HuEoQdYDb3Rp1BNvtyOgjFF7Fvij81c0a9WO3N5tmN6oGfpp/WGuPAvmatfXt7X5/vW1pT0bioAPD8fkq3v7mZrm+vd6O5fwt2JP7kdhb8fXt6hr5fbPtGgv5IQ6Aw9ne7XBosNmtx6q2regjgxf99f5mt7/dNVvrsdAbTsw5Yljub1DHu9ndTobdNExew6OKioKX9c10To9Dj/QKZQ78t7dozHi7vp0QvwMQh5DsRPQC3mgFxSvX6+uWaGU0Gr5tc4G/vkGx7+1u3xwKjAUdclfd1Xq/vd6uN9NVXRiHKO7hhH+7Qe5/u53O8scwMHhr7s365nqLYpzpgpyTjwZafOh3eKbm5vpmsiiT5Afjwn57fYNi/OXNpMh1nMicC/4ORWm71fVmuvjyfOR1+tV+ebNcLa830wVpeKqDD/vN+nqzu9nvpnMca81ZW1GAcH29u941pzZHgw44I7TVfnuz2S33txOa3QDGGfINqZbIZW62y+V0HewjfA0NwDuLdLtb7pY319fTVVgbxZd8noNaydW+bQJsTOgvB8AbE69vb9GYdnk9ne9kBPBNi5bLOa2wWqGx7XaJhonT8YCR5UDOckBB8ub2enM94byIzd3j4hqM+qz17ZRexNvlXm1ukO+stjfTtT4OsOyD98LpObsbFCOvp+t1HR+cD7xTaqubzfXNzW6zmW6A4oR8QcN+eb1crzfr6XzeN1zOQS3yl83m+nY/ndf4AV9Dv0dB2mq/mtBfEPLsKjo+42/RmHy52l5PF2yGBtJonH1g8pXBDRpirZYTrj6EUKjNXKE4YbNc7lbT1d2QczpttdrgSGE14RJEiGL9I98a/u52s1/fbieMExB47gWUDRqbL29vJmw1BSLM1X69vtntN6vpHCfmDzH3uNHcTjgtwj+DvFquN3jjynY6t3kyAefEyG61Xl3vttvpxrfPpse51e76ZrdF/j56W+OkG304o4Pl7Qq5y9ie3tjXwjcHuF+u99tly84kbvTppbxhYCQXI5HcaDghpMO5d+V6hYKv3bUyiLh7BLbNt7frarW82a+XaDQqEV/nreHEouUvdXwpSrjmg77BkzDrzVLick3HHdrJ5rnSlrqERJ5gn9P0q83t/nZ3q5AAuZY7NXx5NyDeW8Bt99XtdrXebDdLiT07JW68tZQT9s1+t73ZX99K7FkoQZONqJyo16v1enm92d9K7MwpYdsCsK+ub9GwYbfbSxw2k8uGtHeoQc47kaR1djYb/g1KaHCAIj2lKB0/1kHgPPHtG0Qobze7m2upO097rrvPDj0ITTmstvv19fXtrcxpQuqbtIkvQ7JjkKvKLW+3eONXy5kJ9dhJWWQdD07KwmX/DfLp/XIvczmdicHJcHRgcw5fVjdLBP32RmJEygQeGr/54BFyE1ivbnabvdTpNop7lvPjIPhHHWdYsI4W7/7B2+0GMbiVOXSnoSAJ/2a/2t8uV0uJfY+sm5d4WtLlFkUAUoc4nDc75y52sGF2nGNzc7/92+98McJ2fbvfbvYyF8JEmRUXwksguNqsd6vNzW4lsRkWJRgcQ+iiDsbzHiUwvEHsljupMbVM37y953XN1XK9x3uQV+raEBm+yU1wtV8t96iT3UqcrFLhmvwEd6hxWe9uZG7Kk+ia2yU3sc0torZZ386IWNMz+fld3Wyvl8vNSmbsqsAzhQoQjTvX1y3HW+fgmWlvwLnks7u5QdHXjEKVzg6dbxvDDT4BKnO+Tl1/zleCm91qtV/L3AEvvUPnI7a6RaP6a5nb9VT15zz8UEe+2qBWc0Y1r7M755oU2N7gzAS7GXV6jd6ci9fNfov3da1mFEF39eacUwk3y+1qeSNzJV1Zd87nmdc7fN6sJcHNSAQzWuiD7iGYgWVyznxera6X+MzfciPx8Fk7GR9cIb0pkLZCyrO8xMETDPXV0jzw7fjcrW43N/u9zJUIOZTW3JSu9jil0vp6NWKlyhPMdOSd4XK4zW653O5vZIyypV35zt4CrDebLU4wJR5bYJNq0dkKTB3nJXvVoiAOkairoxU4zyCAV05pDecl0pIbFLUw2WqBM05qZ8QJ510JIees3PYaxRI3Lb41nHAmn1vXDRABm3MjDV4XX6+JQf/zzT//H8uNmW4==END_SIMPLICITY_STUDIO_METADATA
